---
- name: Disabled scenario example
  disabled: true
  hosts:
    - aws
    - homelab
  tasks:
    - name: Run apt update
      command: apt update
      workingDir: /root
      disabled: true
      logOutput: true

- name: Update homelab scenario
  hosts: homelab
  tasks:
    - name: Echo some command on host
      workingDir: /root
      command: echo "Some command"
    - name: Disabled task
      workingDir: /root
      command: echo "Disabled command"
      disabled: true
