---
scenario2:
  name: Scenario 2 example
  hosts: dev
  tasks:
    list-root-directory:
      workingDir: /root
      logOutput: false
      command: ls -la 2>/dev/null
    list-home-directory:
      workingDir: "."
      logOutput: false
      command: ls -la
