---
- name: Scenario 2 example
  hosts: all
  tasks:
    - name: "list-root-directory"
      workingDir: /root
      logOutput: false
      command: ls -la 2>/dev/null
    - name: "list-home-directory"
      workingDir: "."
      logOutput: false
      command: ls -la
